"""
prompts/pr_description.py

Generates the body of every pull request opened by RepoMind.
The template is designed to give a human reviewer everything they need
to understand, review, and merge the PR without reading the raw diffs.
"""

from __future__ import annotations

from datetime import UTC, datetime

# ── Template ──────────────────────────────────────────────────────────────────
# Sections:
#   Overview      — what changed and why, in plain English
#   Files Changed — formatted file list with reasons
#   Diff Preview  — per-file diff blocks (max 120 lines each)
#   Checklist     — standard review gate for auto-generated PRs
#   Footer        — timestamp + generation attribution

PR_DESCRIPTION_TEMPLATE = """\
## Overview

{summary}

**Reason for change:** {reason}

---

## Files Changed

{changed_files}

---

## Diff Preview

{diff_preview}

---

## Review Checklist

Before merging, please confirm:

- [ ] The changes match the stated intent in the Overview section
- [ ] No unrelated files were modified
- [ ] Logic is correct and no obvious bugs were introduced
- [ ] Existing tests still pass (`pytest tests/ -v`)
- [ ] New behaviour is covered by tests or is trivially correct
- [ ] No secrets, credentials, or personally identifiable information were added

---

## Notes

- This PR was automatically generated by **RepoMind** on {timestamp} UTC
- All changes respect the existing code style, structure, and patterns
- Existing functionality was not removed unless explicitly instructed
- If this PR looks wrong, close it and use `POST /refine` with a correction

"""


def _format_changed_files(changed_files: list[str], reasons: list[str] | None = None) -> str:
    """
    Render the changed-files section.

    If a parallel `reasons` list is provided (one reason per file), each file
    entry gets an explanatory sub-bullet.
    """
    if not changed_files:
        return "_No files were modified._"

    lines: list[str] = []
    for i, path in enumerate(changed_files):
        reason = (reasons[i] if reasons and i < len(reasons) else "") or ""
        if reason:
            lines.append(f"- `{path}` — {reason}")
        else:
            lines.append(f"- `{path}`")
    return "\n".join(lines)


def _format_diff_preview(diff_summary: str | dict, max_lines_per_file: int = 120) -> str:
    """
    Render the diff-preview section.

    Accepts either:
      - A plain string (single diff or pre-formatted summary text)
      - A dict mapping {file_path: diff_text} (from generate_repo_diff)
    """
    if not diff_summary:
        return "_No diff available._"

    if isinstance(diff_summary, str):
        lines = diff_summary.splitlines()
        if len(lines) > max_lines_per_file:
            lines = lines[:max_lines_per_file] + [
                f"... ({len(lines) - max_lines_per_file} more lines truncated)"
            ]
        return "```diff\n" + "\n".join(lines) + "\n```"

    # dict path — one collapsible block per file
    blocks: list[str] = []
    for file_path, diff_text in diff_summary.items():
        if not diff_text.strip():
            continue
        diff_lines = diff_text.splitlines()
        truncated = False
        if len(diff_lines) > max_lines_per_file:
            diff_lines = diff_lines[:max_lines_per_file]
            truncated = True
        preview = "\n".join(diff_lines)
        if truncated:
            preview += f"\n... (diff truncated to {max_lines_per_file} lines)"
        blocks.append(
            f"<details>\n<summary><code>{file_path}</code></summary>\n\n"
            f"```diff\n{preview}\n```\n\n</details>"
        )

    return "\n\n".join(blocks) if blocks else "_No diff available._"


def build_pr_description(
    summary: str,
    reason: str,
    changed_files: list[str],
    diff_summary: str | dict = "",
    file_reasons: list[str] | None = None,
) -> str:
    """
    Build a complete, reviewer-friendly PR description.

    Args:
        summary:       Plain-English summary of what changed (from the instruction).
        reason:        Why the change was made (user instruction or platform context).
        changed_files: Relative file paths of every file touched.
        diff_summary:  Either a raw diff string or a {file_path: diff} dict.
        file_reasons:  Optional list of per-file reasons (same order as changed_files).

    Returns:
        Formatted Markdown string ready to be posted as a GitHub PR body.
    """
    return PR_DESCRIPTION_TEMPLATE.format(
        summary=summary.strip() or "Automated code changes applied by RepoMind.",
        reason=reason.strip() or "Instruction provided by user through HackingTheRepo platform.",
        changed_files=_format_changed_files(changed_files, file_reasons),
        diff_preview=_format_diff_preview(diff_summary),
        timestamp=datetime.now(UTC).strftime("%Y-%m-%d %H:%M"),
    )
